WHEAT:
  isEnable: true
  multiplier: 1
POTATOES:
  isEnable: true
  multiplier: 1
CARROTS:
  isEnable: true
  multiplier: 1
BEETROOTS:
  isEnable: true
  multiplier: 1
COCOA:
  isEnable: true
  multiplier: 1
NETHER_WART:
  isEnable: true
  multiplier: 1